### ISSUE TITLE
Fix "semantic-release" CI failures on merges to main

### ISSUE THREAD

**Issue by sedatbasar** [sixfeetup/scaf#354]
**Background:**
Current pushed to main fails on semantic-release.
e.g https://github.com/sixfeetup/scaf/actions/runs/10490831281/job/29058471741

**AC:**
* Fix the issue

**Comment by gfranxman** [comment]
Error:"""
[3:54:34 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 2 file(s) to commit
[3:54:35 PM] [semantic-release] › ✘  Failed step "prepare" of plugin "@semantic-release/git"
[3:54:35 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://x-access-token:[secure]@github.com/sixfeetup/scaf HEAD:main
remote: error: GH013: Repository rule violations found for refs/heads/main.        
"""

**Comment by gfranxman** [comment]
Rules as: https://github.com/sixfeetup/scaf/rules?ref=refs%2Fheads%2Fmain

**Comment by gfranxman** [comment]
Following the links and warnings,  we need to move from actions/checkout@v3 to @v4 in order to get it to use node20 instead of 16.
However, I think that is a red herring.    
The real failure is when this is called 'git push --tags https://x-access-token:[secure]@github.com/sixfeetup/scaf HEAD:main'
It is trying to push tags to main, but cannot because of the branch protection.
"Required status check "GitHub actions" is expected".    
The rule is here: http://github.com/sixfeetup/scaf/rules?ref=refs%2Fheads%2Fmain which just states "Require branches to be up to date before merging"

These are the branches that were merged: https://github.com/sixfeetup/scaf/pulls?q=is%3Apr+320+321+348+341+340+336
They've been merged to main already so the final step is the tagging, which it has done locally, it just can't push the tag.

This comes down to either "Require branches to be up to date before merging" rule, or "Require status checks to pass".  
I think the main branch is defacto up to date unless one of those node tools actually commit a local change that would get pushed with the tag.   So the other piece is the "require status checks to pass"  which has a section for the checks, but it looks like  none are listed.

I don't have access to inspect or modify anything in this regard, but it looks like either a no op, or the generic "GitHub Actions" tries to run all of the checks recursively?

**Comment by clshaw01** [comment]
Boy howdy is this fun.  Here's our version ci work around:
- We created the app and key, and set the bypass rule.
- Steps 1, 2, and 4 are complete

- https://github.com/orgs/community/discussions/25305#discussioncomment-8256560
